version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'musicly'
    volumes:
      - musicly-postgres:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - app-network

  redis:
    container_name: redis-container
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-network

  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: musicly
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_jwt_secret
      JWT_EXPIRES_IN: 2d
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    volumes:
      - .:/app
    command: ["pnpm", "run", "start:dev"]

networks:
  app-network:
    driver: bridge

volumes:
  musicly-postgres: